# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelCityDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_count_one', models.IntegerField(blank=True, null=True)),
                ('hotel_count_two', models.IntegerField(blank=True, null=True)),
                ('hotel_count_other', models.IntegerField(blank=True, null=True)),
                ('modify_date', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_1', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_2', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_3', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'hotel_city_distribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HotelPriceDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_hotel_count', models.IntegerField(blank=True, null=True)),
                ('middle_hotel_count', models.IntegerField(blank=True, null=True)),
                ('height_hotel_count', models.IntegerField(blank=True, null=True)),
                ('city_type', models.IntegerField(blank=True, null=True)),
                ('modify_date', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_1', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_2', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_3', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'hotel_price_distribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LyCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(blank=True, max_length=45, null=True)),
                ('city_name', models.CharField(blank=True, max_length=45, null=True)),
                ('city_py', models.CharField(blank=True, max_length=45, null=True)),
                ('modify_time', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_1', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_2', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_3', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ly_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LyHotCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(blank=True, max_length=45, null=True)),
                ('city_name', models.CharField(blank=True, max_length=45, null=True)),
                ('youji_count', models.IntegerField(blank=True, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('crawl_time', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col1', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col2', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col3', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ly_hot_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestmodelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'testmodel_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('e_mail', models.CharField(blank=True, max_length=45, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_1', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_2', models.CharField(blank=True, max_length=45, null=True)),
                ('reserve_col_3', models.CharField(blank=True, max_length=45, null=True)),
                ('create_date', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
